name: CI
on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        shell: 'script -q -e -c "bash {0}"' # https://github.com/actions/runner/issues/241
        run: make all
